### ISSUE TITLE
Grafana configuration changes

### ISSUE THREAD

**Issue by tricorder-eng** [tricorder-observability/Starship#8]
[Grafana helm chart .ini](https://github.com/grafana/helm-charts/blob/2987944b43d77f9081fe7d7be40179e281df3917/charts/grafana/values.yaml#L692)
[Min refresh internal](https://grafana.com/docs/grafana/v7.5/administration/configuration/#min_refresh_interval)
[Another discussion on reducing refresh rate](https://community.grafana.com/t/auto-refresh-lower-than-5s/32384)

Another approach through environment variable
[Additional discussion](https://community.home-assistant.io/t/home-assistant-grafana-dashboard-refresh-rate/358947/8)
```
env_vars:
  - name: GF_MIN_REFRESH_INTERVAL
    value: 1s
  - name: GF_DASHBOARDS_MIN_REFRESH_INTERVAL
    value: 1s
```
